### PR TITLE
Update schedule on website for 2019-2020

### PR DESCRIPTION
**Pull request by jackbuehner**
This pull request updates the schedule and event dates on the website to the new events and dates released at the banquet last Wednesday. Additionally, it adds events that were previously not listed on the website and places a card on the home page announcing the new schedule.

### Visible Changes
- replace old camping schedule with new camping schedule
- update dates for pine straw and merit badge clinic
- add times for Patrol Leaders' Council meetings
- add times for Troop Committee meetings
- add additional dates:
	- SOLO Wilderness First Aid
	- Hornaday Conservation Weekend
	- Phoenix District Webelos WOW
	- CPR Saturday
	- Parent's Night & Camp Kick Off
	- Scout Sunday
- add banner on home page for new schedule

### Code Changes
- Staticrpyt, the service which encrypts our encrypted pages, changed it's encryption method. As a result, I created a new layout file at `_layouts\encrypted-v2.html` that has the updated code. New or updated pages (in this case, the Calendar page) must use `layout: encrypted-v2` instead of `layout: encrypted`.
- The indented dates on the Calendar page are no longer line breaks with several spaces after them. This created the undesired effect of text wrapping on mobile and not being indented on the second line. Now, these dates are in a `span` element with `class="indent--new-line"` within the `p` element.

### Visual Comparison
Click on the images for the full size

|Before|After|
|---|---|
|image|image|
|image|image|

### CODE REVIEW

**Comment by jackbuehner** [comment]
How does this look? This is a major website change, so I need your approval to push this out.

@Gulluk @nedcoleman1234

**Comment by nedcoleman1234** [comment]
Looks great Jack! Thanks for doing this. You’re all good to implement it.

Thanks-
Ned Coleman

**Comment by jackbuehner** [comment]
All set! Thanks @nedcoleman1234 for your quick response.

**Comment by evansclan** [comment]
I see a couple of things to fix: Under the December campout it should be "retreat" not "retreet". On the merit badge clinic dates the years should be 2019 and 2020 rather than 2018 and 2019.

**Comment by jackbuehner** [comment]
Thanks @evansclan for letting me know. It should fixed and released in just a few minutes once some build checks pass. The fix can be tracked at Pull Request #78

**Pull request merged**
