### PR TITLE
Create a communication information page with commuication methods and social media links

### LINKED ISSUE #16: Replace weekly newsletters page with a communication overview page
Currently, the weekly newsletters page just had a button to sign up for the emails. A revamped page should include the email sign-up, the remind sign-up, and a join link for the Facebook group. It should also mention other social media and the SmugMug.

The new page should be named `communication.html`. In the renaming process, it is import that `email-newsletters.html` is redirected to `communication.html`.

The work for this should occur on a different branch and be tested once completed before deployment to the master branch.

### PR DESCRIPTION
**Pull request by jackbuehner**
resolves #16

### CODE REVIEW

**Comment by jackbuehner** [comment]
Note that since this branch is from before the redesign, cloning it and viewing it will result it styling errors on several pages. However, it will display the new communication page normally.

**Comment by jackbuehner** [comment]
@Gulluk Is this approved?

Below is a before vs after comparison of the changes:

| Before  | After |
| ------------- | ------------- |
| weekly newsletters-1  | communication-1  |

**Review by quintoncables — APPROVED** [review]
looks good on my end! great job!

**Comment by jackbuehner** [comment]
Approval from Logan:
Approval from Logan

**Pull request merged**
